import React, { useMemo, useState } from 'react';
import { ArrowRight, Check, Coins, Flame, Plus, Sparkles, Trophy, Zap } from 'lucide-react';
import { levelFromXp } from '../data/seed';
import { formatTime } from '../utils/formatting';
import '../styles/pages.css';

export const Home: React.FC<any> = ({ appState }) => {
  const { state, completeQuest } = appState;
  const [toast, setToast] = useState('');
  const level = levelFromXp(state.xp);
  const active = state.quests.filter((q: any) => q.status === 'active');
  const completed = state.quests.length - active.length;
  const quickWin = state.quickWins[0];
  const finish = (id: string, name: string) => { completeQuest(id); setToast(`${name} complete · XP and coins added`); setTimeout(() => setToast(''), 2200); };
  return <div className="page">
    <header className="topbar"><div><p className="eyebrow">{new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</p><h1>Good morning, {state.profile.name} <span>✦</span></h1><p className="muted">Your next small step is waiting.</p></div><div className="top-actions"><span className="coin-pill">🪙 {state.coins}</span><div className="avatar">{state.profile.avatar}</div></div></header>
    {toast && <div className="toast" role="status"><Check size={16}/> {toast}</div>}
    <section className="hero-card"><div className="hero-copy"><span className="badge badge-light">LEVEL {level.level} · {state.profile.title}</span><h2>Make today<br/><em>count.</em></h2><p>Every quest is a vote for the person you are becoming.</p><div className="xp-line"><span>XP to next level</span><strong>{level.xpIntoLevel} / {level.xpToNext}</strong></div><div className="progress-bar"><div className="progress-bar-fill" style={{ width: `${Math.round(level.xpIntoLevel / level.xpToNext * 100)}%` }}/></div></div><div className="hero-orb">{state.profile.avatar}<span>✦</span></div></section>
    <div className="stat-row"><div className="stat-card"><Flame size={18}/><strong>{state.streak}</strong><span>day streak</span></div><div className="stat-card"><Trophy size={18}/><strong>{completed}</strong><span>quests done</span></div><div className="stat-card"><Sparkles size={18}/><strong>{state.regions.filter((r: any) => r.unlocked).length}</strong><span>regions found</span></div></div>
    <div className="section-heading"><div><p className="eyebrow">YOUR FOCUS</p><h2>Today's journey</h2></div><button className="text-button">See all <ArrowRight size={16}/></button></div>
    <div className="quest-list">{active.slice(0, 3).map((quest: any) => <article className="quest-card" key={quest.id}><div className="quest-icon" data-category={quest.category}>{quest.category === 'Health' ? '🌿' : quest.category === 'Learning' ? '📚' : '🏠'}</div><div className="quest-main"><div className="quest-title"><h3>{quest.name}</h3><span className="difficulty">{quest.difficulty === 'easy' ? '⭐' : '⭐⭐'}</span></div><p>{quest.description}</p><div className="quest-meta"><span>{quest.category}</span>{quest.timeEstimate && <span>◷ {formatTime(quest.timeEstimate)}</span>}<span className="reward">+{quest.xpReward} XP · 🪙 {quest.coinReward}</span></div></div><button className="check-button" onClick={() => finish(quest.id, quest.name)} aria-label={`Complete ${quest.name}`}><Check size={20}/></button></article>)}</div>
    <div className="quick-win"><div className="quick-icon"><Zap size={21}/></div><div><span className="eyebrow">NEED A QUICK WIN?</span><h3>{quickWin}</h3><p>2 minutes · +10 XP</p></div><button className="btn btn-primary btn-sm" onClick={() => setToast('Quick win logged · +10 XP')}>Do it <ArrowRight size={15}/></button></div>
  </div>;
};

export const JourneyPage: React.FC<any> = ({ appState }) => { const { state } = appState; return <div className="page"><header className="topbar"><div><p className="eyebrow">THE LONG VIEW</p><h1>Your Journey</h1><p className="muted">A map of the life you're building.</p></div><div className="avatar">{state.profile.avatar}</div></header><section className="map-card"><div className="map-header"><div><span className="badge badge-light">CURRENT REGION</span><h2>Habit Forest</h2><p>Small, consistent actions grow into something strong.</p></div><span className="map-big-icon">🌲</span></div><div className="journey-path">{state.regions.map((region: any, index: number) => <div className={`region ${region.unlocked ? 'unlocked' : 'locked'}`} key={region.id}><div className="region-node">{region.unlocked ? region.icon : '🔒'}</div><div className="region-info"><strong>{region.name}</strong><span>{region.description}</span><div className="progress-bar"><div className="progress-bar-fill" style={{ width: `${region.progress}%` }}/></div></div>{index < state.regions.length - 1 && <div className="path-line"/>}</div>)}</div></section><section className="section-heading"><div><p className="eyebrow">YOUR COMPANION</p><h2>A little encouragement</h2></div></section><div className="companion card"><span className="companion-avatar">🦊</span><div><h3>You're doing better than you think.</h3><p className="muted">Your forest is growing one small action at a time. Keep the next step tiny.</p></div></div></div>; };

export const QuestsPage: React.FC<any> = ({ appState }) => { const { state, completeQuest, createQuest, deleteQuest } = appState; const [show, setShow] = useState(false); const [filter, setFilter] = useState('all'); const [name, setName] = useState(''); const [category, setCategory] = useState('Personal Growth'); const filtered = state.quests.filter((q: any) => filter === 'all' || q.type === filter); const submit = (e: React.FormEvent) => { e.preventDefault(); if (!name.trim()) return; createQuest({ id: `quest-${Date.now()}`, name, description: 'A quest you chose for yourself.', type: 'personal', category, difficulty: 'moderate', xpReward: 35, coinReward: 12, progress: 0, target: 1, status: 'active', repeat: 'weekly', timeEstimate: 15, subtasks: [], createdAt: new Date().toISOString() }); setName(''); setShow(false); }; return <div className="page"><header className="topbar"><div><p className="eyebrow">YOUR ADVENTURES</p><h1>Quests</h1><p className="muted">Choose a quest. Build your momentum.</p></div><button className="btn btn-primary" onClick={() => setShow(!show)}><Plus size={17}/> New quest</button></header>{show && <form className="card quest-form" onSubmit={submit}><div className="section-heading"><h2>Create a quest</h2><button type="button" className="icon-button" onClick={() => setShow(false)}>×</button></div><label>Quest name<input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="What would feel good to finish?"/></label><label>Category<select value={category} onChange={e => setCategory(e.target.value)}><option>Personal Growth</option><option>Health</option><option>Home</option><option>Learning</option><option>Work</option></select></label><button className="btn btn-primary btn-full">Add quest</button></form>}<div className="filter-row">{['all','daily','weekly','personal','quick'].map(f => <button key={f} className={`filter ${filter === f ? 'selected' : ''}`} onClick={() => setFilter(f)}>{f}</button>)}</div><div className="quest-list">{filtered.map((q: any) => <article className={`quest-card ${q.status === 'completed' ? 'is-complete' : ''}`} key={q.id}><div className="quest-icon">{q.status === 'completed' ? '✓' : '⚔️'}</div><div className="quest-main"><div className="quest-title"><h3>{q.name}</h3><span className="badge badge-primary">{q.type}</span></div><p>{q.description}</p><div className="quest-meta"><span>{q.category}</span><span>{q.xpReward} XP</span><span>🪙 {q.coinReward}</span></div></div><div className="quest-actions">{q.status === 'active' && <button className="check-button" onClick={() => completeQuest(q.id)}><Check size={20}/></button>}<button className="delete-button" onClick={() => deleteQuest(q.id)} aria-label="Delete quest">×</button></div></article>)}</div></div>; };

export const ProgressPage: React.FC<any> = ({ appState }) => { const { state } = appState; const done = state.quests.filter((q: any) => q.status === 'completed').length; const categories = [...new Set(state.quests.map((q: any) => q.category))]; return <div className="page"><header className="topbar"><div><p className="eyebrow">THE BIG PICTURE</p><h1>Your progress</h1><p className="muted">Notice what is already changing.</p></div></header><div className="metric-grid"><div className="metric-card purple"><span>✦</span><strong>{state.xp}</strong><small>total XP earned</small></div><div className="metric-card gold"><span>🪙</span><strong>{state.coins}</strong><small>coins available</small></div><div className="metric-card green"><span>⚔️</span><strong>{done}</strong><small>quests completed</small></div><div className="metric-card pink"><span>🔥</span><strong>{state.longestStreak}</strong><small>longest streak</small></div></div><section className="card chart-card"><div className="section-heading"><div><p className="eyebrow">LAST 7 DAYS</p><h2>Activity rhythm</h2></div><span className="badge badge-success">On track</span></div><div className="bars">{[38,55,42,76,62,88,68].map((n, i) => <div className="bar-wrap" key={i}><div className="bar" style={{height: `${n}%`}}/><span>{['M','T','W','T','F','S','S'][i]}</span></div>)}</div></section><section><div className="section-heading"><div><p className="eyebrow">BY CATEGORY</p><h2>Where energy goes</h2></div></div><div className="category-list">{categories.map((c: any, i) => <div className="category-row" key={c}><span>{['🌿','📚','🏠','💼'][i % 4]}</span><strong>{c}</strong><div className="progress-bar"><div className="progress-bar-fill" style={{width: `${Math.min(92, 30 + i * 18)}%`}}/></div><small>{Math.min(92, 30 + i * 18)}%</small></div>)}</div></section></div>; };

export const ProfilePage: React.FC<any> = ({ appState, setTheme, theme }) => { const { state, updateProfile, redeemReward, createReward } = appState; const [shop, setShop] = useState(false); const [rewardName, setRewardName] = useState(''); return <div className="page"><header className="profile-header"><div className="profile-avatar">{state.profile.avatar}</div><div><p className="eyebrow">LEVEL {state.level} {state.profile.title}</p><h1>{state.profile.name}</h1><p className="muted">Your journey, your rules.</p></div></header><section className="card profile-card"><div className="section-heading"><div><p className="eyebrow">REWARD SHOP</p><h2>Spend your coins</h2></div><span className="coin-pill">🪙 {state.coins}</span></div>{state.rewards.map((r: any) => <div className="reward-row" key={r.id}><span className="reward-emoji">{r.category === 'Leisure' ? '🎬' : '☕'}</span><div><strong>{r.name}</strong><p>{r.description}</p></div><button className="btn btn-secondary btn-sm" disabled={state.coins < r.price} onClick={() => redeemReward(r.id)}>{r.price} 🪙</button></div>)}<button className="text-button" onClick={() => setShop(!shop)}><Plus size={15}/> Create your own reward</button>{shop && <form className="inline-form" onSubmit={e => {e.preventDefault(); if (!rewardName) return; createReward({id:`reward-${Date.now()}`,name:rewardName,description:'A reward you designed.',price:100,category:'Custom',redeemedCount:0,createdAt:new Date().toISOString()});setRewardName('');setShop(false)}}><input value={rewardName} onChange={e => setRewardName(e.target.value)} placeholder="Reward name"/><button className="btn btn-primary btn-sm">Add</button></form>}</section><section className="card settings-card"><div className="section-heading"><div><p className="eyebrow">SETTINGS</p><h2>Make it yours</h2></div></div><label>Your name<input value={state.profile.name} onChange={e => updateProfile({name:e.target.value})}/></label><div className="theme-options"><span>Appearance</span>{(['light','dark','system'] as const).map(t => <button key={t} className={theme === t ? 'selected' : ''} onClick={() => setTheme(t)}>{t === 'light' ? '☀️' : t === 'dark' ? '🌙' : '⚙️'} {t}</button>)}</div></section><section className="card achievements"><div className="section-heading"><div><p className="eyebrow">COLLECTION</p><h2>Achievements</h2></div></div><div className="achievement-grid">{state.achievements.map((a: any) => <div className={`achievement ${a.unlocked ? '' : 'locked'}`} key={a.id}><span>{a.unlocked ? a.icon : '🔒'}</span><strong>{a.title}</strong><small>{a.description}</small></div>)}</div></section></div>; };
